Pushoff keep alive on ack received
awslabs/aws-c-mqtt pull request #314
Opened 2023-08-08 15:57 UTC by xiazhvera

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-08 16:06 UTC, bretambrose requested changes
The write timestamp can't be shared/singleton.

If I send 5 publishes at times 1, 2, 3, 4, 5.  And then an ack comes back for the first one, the push out needs to be based on the first one's write stamp (1).

2023-08-08 17:17 UTC, xiazhvera commented
> The write timestamp can't be shared/singleton.
> 
> If I send 5 publishes at times 1, 2, 3, 4, 5. And then an ack comes back for the first one, the push out needs to be based on the first one's write stamp (1).

I dont think it matters, we only need to push off based on the "last" write time since that's when our "last transmission" happened.

2023-08-08 17:21 UTC, bretambrose commented
> > The write timestamp can't be shared/singleton.
> > If I send 5 publishes at times 1, 2, 3, 4, 5. And then an ack comes back for the first one, the push out needs to be based on the first one's write stamp (1).
> 
> I dont think it matters, we only need to push off based on the "last" write time since that's when our "last transmission" happened.



> > The write timestamp can't be shared/singleton.
> > If I send 5 publishes at times 1, 2, 3, 4, 5. And then an ack comes back for the first one, the push out needs to be based on the first one's write stamp (1).
> 
> I dont think it matters, we only need to push off based on the "last" write time since that's when our "last transmission" happened.

It absolutely matters.  If the connect is dropped at time 1.5 then the ping cannot be pushed out farther than that.

2023-08-09 17:18 UTC, bretambrose commented on tests/v3/connection_state_test.c
> + * Makes a CONNECT, with 1 second keep alive ping interval, send a different operation every second, and then ensure NO
If this comment is accurate then I feel like this test is likely overly sensitive to timing conditions and containerization.

2023-08-09 17:18 UTC, bretambrose commented on tests/v3/connection_state_test.c
> + * 4 ping
This is alarming.  Given a keep aliveof 1 second and a ping timeout of 100ms we should be seeing multiple disconnections which are going to disrupt the logical simplicity of the test.

2023-08-09 17:18 UTC, bretambrose commented on tests/v3/connection_state_test.c
> +    aws_thread_current_sleep(1000000000);
I don't see any asserts in this test actually checking anything meaningful.

2023-08-09 21:15 UTC, xiazhvera commented
Updated the unit tests.

2023-08-10 15:03 UTC, bretambrose approved these changes
Fix comment and ship

2023-08-10 15:03 UTC, bretambrose commented on tests/v3/connection_state_test.c
> +        /* Publish qos1*/
qos0

2023-08-10 17:16 UTC, merged